FROM alpine:3.19
RUN addgroup -S geryon && adduser -S -G geryon -u 65534 geryon
COPY geryon /geryon
COPY --from=alpine:3.19 /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
USER geryon
EXPOSE 5432 3306 1433 8080 9090
HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \
  CMD wget -qO- http://localhost:8080/api/v1/health || exit 1
ENTRYPOINT ["/geryon"]
